spring:
  application:
    name: slangbuddy

  data:
    uri: mongodb://localhost:27017/alham_mongo
    database: alham_mongo

  ai:
    openai:
      api-key: 
      chat:
        options:
          model: gpt-4o-mini
        enabled: true